# AppVeyor build configuration
# http://www.appveyor.com/docs/build-configuration
os: unstable
skip_tags: true

install:
  - set QTDIR=C:\Qt\5.4\mingw491_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - cd game
  - qmake DEFINES+=INTEGRATION_TESTS
  - mingw32-make
