environment:
  matrix:
    - QTDIR: C:\Qt\5.11\msvc2015
      CMD_VCVARSALL: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSVC_PLATFORM: "x86"
    - QTDIR: C:\Qt\5.11\msvc2017_64
      CMD_VCVARSALL: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSVC_PLATFORM: "x64"
       
configuration:
  - release

# Get the project submodules
# Set the environment variables and paths to make
install:
  - git submodule update --init --recursive
  - dir %QTDIR%
  - call %CMD_VCVARSALL%
  - set PATH=%PATH%;%QTDIR%\bin

# Run qmake
before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd game
  - qmake game.pro


# Build the projects
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd game
  - nmake
  
  
after_build:
  - cd %APPVEYOR_BUILD_FOLDER%\game\release
  - mkdir release
  - cd release
  - xcopy %APPVEYOR_BUILD_FOLDER%\game\release\SameWorld.exe %APPVEYOR_BUILD_FOLDER%\game\release\release\
  - windeployqt SameWorld.exe
  

artifacts:
  - path: game\release\release
  - name:%MSVC_PLATFORM%-release.zip


 
 
  
  
  

