environment:
  matrix:
    - QTDIR: C:\Qt\5.6\msvc2015_64
      cname: Win64-VS2015
      VSVER: 14.0
      PT: v140
    - QTDIR: C:\Qt\5.6\msvc2015
      cname: Win32-VS2015
      VSVER: 14.0
      PT: v140

configuration:
  - release

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %cname%==mingw set make=mingw32-make.exe
  - if %cname%==mingw g++ --version
  - if %cname%==mingw %make% --version
  - if not %cname%==mingw call "%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ARCH%
  - if not %cname%==mingw set make=nmake.exe
  - if not %cname%==mingw %make% /? > nul

before_build:
  - if %cname%==mingw set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\shared
  - cd %APPVEYOR_BUILD_FOLDER%\game
  - qmake -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\game
  - '%make%'
  # Also, build vcxproj (without qt)
  - if not %cname%==mingw msbuild /m /p:Configuration=%CONFIGURATION% /p:Platform=%ARCH% pointing.vcxproj /p:PlatformToolset=%PT% /t:Rebuild

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\tests
  - qmake -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION%
  - '%make% check -s'


