# AppVeyor build configuration
# http://www.appveyor.com/docs/build-configuration
os: unstable
skip_tags: true


  
install:
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - qmake untitled.pro
  - mingw32-make
