# AppVeyor build configuration
# http://www.appveyor.com/docs/build-configuration

image: Visual Studio 2017
branches:
  only:
    - master
    

environment:
  matrix:
  - QT5: C:\Qt\5.3\mingw482_32
    MINGW: C:\Qt\Tools\mingw482_32
  - QT5: C:\Qt\5.4\mingw491_32
    MINGW: C:\Qt\Tools\mingw491_32
  - QT5: C:\Qt\5.5\mingw492_32
    MINGW: C:\Qt\Tools\mingw492_32
  - QT5: C:\Qt\5.6\mingw49_32
    MINGW: C:\Qt\Tools\mingw492_32
  - QT5: C:\Qt\5.7\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
    
install:
  - set QTDIR=C:\Qt\5.10.1\msvc2017_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;

 
 
build_script:
  - cd game
  - qmake untitled.pro
  - mingw32-make
