# AppVeyor build configuration
# http://www.appveyor.com/docs/build-configuration

image: Visual Studio 2017
branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.10.1\msvc2017_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;

 
 
build_script:
  - cd game
  - qmake untitled.pro
  - mingw32-make
